# Generated by Django 4.2.30 on 2026-06-09 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('direccion', models.TextField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('representante_legal', models.CharField(blank=True, max_length=200)),
                ('regimen', models.CharField(choices=[('comun', 'Régimen Común'), ('simplificado', 'Régimen Simplificado')], default='comun', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('contador', 'Contador'), ('auxiliar', 'Auxiliar Contable'), ('gerente', 'Gerente'), ('vendedor', 'Vendedor')], default='auxiliar', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de Empresa',
                'verbose_name_plural': 'Usuarios de Empresa',
                'unique_together': {('usuario', 'empresa')},
            },
        ),
    ]
