# Generated by Django 4.2.30 on 2026-06-08 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('factura_vencer', 'Factura por Vencer'), ('factura_vencida', 'Factura Vencida'), ('stock_bajo', 'Stock Bajo'), ('pago_recibido', 'Pago Recibido'), ('pago_realizado', 'Pago Realizado'), ('nomina_pendiente', 'Nómina Pendiente'), ('activo_depreciado', 'Activo Totalmente Depreciado'), ('cotizacion_vencer', 'Cotización por Vencer'), ('sistema', 'Notificación del Sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('leida', models.BooleanField(default=False)),
                ('email_enviado', models.BooleanField(default=False)),
                ('url_accion', models.CharField(blank=True, max_length=200)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_facturas_vencer', models.BooleanField(default=True)),
                ('email_facturas_vencidas', models.BooleanField(default=True)),
                ('email_stock_bajo', models.BooleanField(default=True)),
                ('email_pagos', models.BooleanField(default=True)),
                ('email_nomina', models.BooleanField(default=True)),
                ('email_cotizaciones', models.BooleanField(default=True)),
                ('dias_anticipacion_factura', models.IntegerField(default=5)),
                ('dias_anticipacion_cotizacion', models.IntegerField(default=3)),
                ('sistema_stock_bajo', models.BooleanField(default=True)),
                ('sistema_facturas_vencer', models.BooleanField(default=True)),
                ('sistema_pagos', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
    ]
