# Generated by Django 4.2.30 on 2026-06-09 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('contabilidad', '0004_movimientocontable_centro_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centros_costo', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='cuentapuc',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_puc', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='centrocosto',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentapuc',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='centrocosto',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='cuentapuc',
            unique_together={('empresa', 'codigo')},
        ),
    ]
