# Generated by Django 4.2.30 on 2026-06-14 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0002_datos_iniciales'),
        ('contabilidad', '0005_asientocontable_empresa_centrocosto_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierrePeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('cerrado_at', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres_periodo', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Cierre de Período',
                'verbose_name_plural': 'Cierres de Período',
                'ordering': ['-periodo'],
                'unique_together': {('empresa', 'periodo')},
            },
        ),
    ]
