# Generated by Django 4.2.30 on 2026-06-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagorealizado',
            options={'ordering': ['-fecha'], 'verbose_name': 'Pago Realizado', 'verbose_name_plural': 'Pagos Realizados'},
        ),
        migrations.AlterModelOptions(
            name='pagorecibido',
            options={'ordering': ['-fecha'], 'verbose_name': 'Pago Recibido', 'verbose_name_plural': 'Pagos Recibidos'},
        ),
    ]
