# Generated by Django 4.2.30 on 2026-06-14 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0003_cuentaporcobrar_empresa_cuentaporpagar_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoProntoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dias_plazo', models.IntegerField()),
                ('fecha_limite', models.DateField()),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aplicado', models.BooleanField(default=False)),
                ('fecha_aplicacion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='cartera.cuentaporcobrar')),
            ],
            options={
                'verbose_name': 'Descuento por Pronto Pago',
                'verbose_name_plural': 'Descuentos por Pronto Pago',
                'ordering': ['fecha_limite'],
            },
        ),
    ]
