# Generated by Django 4.2.30 on 2026-06-09 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terceros', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='nit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='tercero',
            unique_together={('empresa', 'nit')},
        ),
    ]
