# Generated by Django 4.2.30 on 2026-06-07 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0004_movimientocontable_centro_costo'),
        ('facturacion', '0003_detallefactura_producto_nullable'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_compra', models.DateField()),
                ('fecha_inicio_depreciacion', models.DateField()),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_residual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vida_util_años', models.IntegerField()),
                ('metodo_depreciacion', models.CharField(choices=[('linea_recta', 'Línea Recta'), ('reduccion_saldos', 'Reducción de Saldos'), ('suma_digitos', 'Suma de Dígitos de los Años')], default='linea_recta', max_length=20)),
                ('valor_depreciado_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_en_libros', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('depreciado', 'Totalmente Depreciado'), ('dado_baja', 'Dado de Baja'), ('vendido', 'Vendido')], default='activo', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('vida_util_años', models.IntegerField()),
                ('metodo_depreciacion', models.CharField(choices=[('linea_recta', 'Línea Recta'), ('reduccion_saldos', 'Reducción de Saldos'), ('suma_digitos', 'Suma de Dígitos de los Años')], default='linea_recta', max_length=20)),
                ('cuenta_activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_activo', to='contabilidad.cuentapuc')),
                ('cuenta_depreciacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_depreciacion', to='contabilidad.cuentapuc')),
                ('cuenta_gasto_depreciacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_gasto_dep', to='contabilidad.cuentapuc')),
            ],
            options={
                'verbose_name': 'Categoría de Activo',
                'verbose_name_plural': 'Categorías de Activos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BajaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('valor_venta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('utilidad_perdida', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baja', to='activos.activofijo')),
                ('asiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_activos', to='contabilidad.asientocontable')),
            ],
            options={
                'verbose_name': 'Baja de Activo',
                'verbose_name_plural': 'Bajas de Activos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='activofijo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.categoriaactivo'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='cuenta_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='contabilidad.cuentapuc'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='cuenta_depreciacion_acumulada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dep_acumulada', to='contabilidad.cuentapuc'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='cuenta_gasto_depreciacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gasto_dep', to='contabilidad.cuentapuc'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='factura_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_comprados', to='facturacion.factura'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_vendidos', to='terceros.tercero'),
        ),
        migrations.CreateModel(
            name='DepreciacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('valor_depreciacion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_acumulado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_en_libros', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aplicada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciaciones', to='activos.activofijo')),
                ('asiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciaciones', to='contabilidad.asientocontable')),
            ],
            options={
                'verbose_name': 'Depreciación Mensual',
                'verbose_name_plural': 'Depreciaciones Mensuales',
                'ordering': ['-periodo'],
                'unique_together': {('activo', 'periodo')},
            },
        ),
    ]
