# Generated by Django 4.2.30 on 2026-06-09 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activos_fijos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='categoriaactivo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_activos', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='activofijo',
            unique_together={('empresa', 'codigo')},
        ),
    ]
