# Generated by Django 4.2.30 on 2026-06-08 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0004_movimientocontable_centro_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('saldo_extracto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_libros', models.DecimalField(decimal_places=2, max_digits=15)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('finalizada', 'Finalizada')], default='borrador', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalizada_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conciliación Bancaria',
                'verbose_name_plural': 'Conciliaciones Bancarias',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('corriente', 'Cuenta Corriente'), ('ahorros', 'Cuenta de Ahorros'), ('fiduciaria', 'Cuenta Fiduciaria')], max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias', to='contabilidad.cuentapuc')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ExtractoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('saldo_inicial_extracto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_final_extracto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_debitos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_creditos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Conciliar'), ('conciliado', 'Conciliado'), ('parcial', 'Parcialmente Conciliado')], default='pendiente', max_length=20)),
                ('archivo_original', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extractos', to='bancos.cuentabancaria')),
            ],
            options={
                'verbose_name': 'Extracto Bancario',
                'verbose_name_plural': 'Extractos Bancarios',
                'ordering': ['-periodo_fin'],
            },
        ),
        migrations.CreateModel(
            name='PartidaConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cheque_girado', 'Cheque Girado No Cobrado'), ('deposito_transito', 'Depósito en Tránsito'), ('nota_debito', 'Nota Débito Banco No Registrada'), ('nota_credito', 'Nota Crédito Banco No Registrada'), ('error_libros', 'Error en Libros'), ('error_banco', 'Error del Banco'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, help_text='Con signo: positivo aumenta el saldo del lado que afecta, negativo lo disminuye', max_digits=15)),
                ('afecta', models.CharField(choices=[('extracto', 'Extracto'), ('libros', 'Libros')], max_length=10)),
                ('resuelta', models.BooleanField(default=False)),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='bancos.conciliacionbancaria')),
            ],
            options={
                'verbose_name': 'Partida de Conciliación',
                'verbose_name_plural': 'Partidas de Conciliación',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('conciliado', models.BooleanField(default=False)),
                ('asiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bancarios', to='contabilidad.asientocontable')),
                ('extracto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='bancos.extractobancario')),
            ],
            options={
                'verbose_name': 'Movimiento Bancario',
                'verbose_name_plural': 'Movimientos Bancarios',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones', to='bancos.cuentabancaria'),
        ),
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='extracto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones', to='bancos.extractobancario'),
        ),
    ]
