# Generated by Django 4.2.30 on 2026-06-09 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('bancos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones_bancarias', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='extractobancario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractos_bancarios', to='empresas.empresa'),
        ),
    ]
