# Generated by Django 4.2.30 on 2026-06-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liquidacionnomina',
            unique_together={('empleado', 'periodo_inicio', 'periodo_fin')},
        ),
    ]
