# Generated by Django 4.2.30 on 2026-06-09 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('nomina', '0002_alter_liquidacionnomina_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='liquidacionnomina',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_nomina', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('empresa', 'cedula')},
        ),
    ]
