# Generated by Django 4.2.30 on 2026-06-14 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_factura_empresa_alter_factura_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=20),
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('consignacion', 'Consignación'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('otro', 'Otro')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField()),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('observacion', models.TextField(blank=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'ordering': ['fecha'],
            },
        ),
    ]
