# Generated by Django 4.2.30 on 2026-06-14 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_tercero_empresa_alter_tercero_nit_and_more'),
        ('contabilidad', '0007_flujocaja'),
        ('empresas', '0002_datos_iniciales'),
        ('facturacion', '0005_alter_factura_estado_mediopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recibido', 'Anticipo Recibido'), ('entregado', 'Anticipo Entregado')], max_length=20)),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_disponible', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('aplicado', 'Aplicado'), ('devuelto', 'Devuelto')], default='activo', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anticipos', to='contabilidad.cuentapuc')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anticipos', to='empresas.empresa')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipos', to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'Anticipo',
                'verbose_name_plural': 'Anticipos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ResolucionDIAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_resolucion', models.CharField(max_length=50)),
                ('fecha_resolucion', models.DateField()),
                ('fecha_inicio_vigencia', models.DateField()),
                ('fecha_fin_vigencia', models.DateField()),
                ('prefijo', models.CharField(blank=True, max_length=10)),
                ('consecutivo_desde', models.IntegerField()),
                ('consecutivo_hasta', models.IntegerField()),
                ('consecutivo_actual', models.IntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra')], default='venta', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones_dian', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Resolución DIAN',
                'verbose_name_plural': 'Resoluciones DIAN',
                'ordering': ['-fecha_resolucion'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionAnticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aplicado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anticipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='facturacion.anticipo')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipos_aplicados', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Aplicación de Anticipo',
                'verbose_name_plural': 'Aplicaciones de Anticipo',
                'ordering': ['-fecha'],
            },
        ),
    ]
